//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorsv1alpha1 "github.com/operator-framework/api/pkg/operators/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolSyncAddOnConfig) DeepCopyInto(out *VolSyncAddOnConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(VolSyncAddOnConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolSyncAddOnConfig.
func (in *VolSyncAddOnConfig) DeepCopy() *VolSyncAddOnConfig {
	if in == nil {
		return nil
	}
	out := new(VolSyncAddOnConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolSyncAddOnConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolSyncAddOnConfigList) DeepCopyInto(out *VolSyncAddOnConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolSyncAddOnConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolSyncAddOnConfigList.
func (in *VolSyncAddOnConfigList) DeepCopy() *VolSyncAddOnConfigList {
	if in == nil {
		return nil
	}
	out := new(VolSyncAddOnConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolSyncAddOnConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolSyncAddOnConfigSpec) DeepCopyInto(out *VolSyncAddOnConfigSpec) {
	*out = *in
	if in.SubscriptionConfig != nil {
		in, out := &in.SubscriptionConfig, &out.SubscriptionConfig
		*out = new(operatorsv1alpha1.SubscriptionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolSyncAddOnConfigSpec.
func (in *VolSyncAddOnConfigSpec) DeepCopy() *VolSyncAddOnConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VolSyncAddOnConfigSpec)
	in.DeepCopyInto(out)
	return out
}
