apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .OperatorName }}
  namespace: {{ .InstallNamespace }}
spec:
{{- if .Channel }}
  channel: {{ .Channel }}
{{- end}}
  installPlanApproval: {{ .InstallPlanApproval }}
  name: {{ .OperatorName }}
  source: {{ .CatalogSource }}
  sourceNamespace: {{ .CatalogSourceNamespace }}
{{- if .StartingCSV }}
  startingCSV: {{ .StartingCSV }}
{{- end}}
{{- if or .NodeSelector .Tolerations .ResourceRequests .ResourceLimits}}
  config:
  {{- if .NodeSelector }}
    nodeSelector:
    {{- range $key, $value := .NodeSelector }}
      "{{ $key }}": "{{ $value }}"
    {{- end }}
  {{- end }}
  {{- if .Tolerations }}
    tolerations:
    {{- range $toleration := .Tolerations }}
    - key: "{{ $toleration.Key }}"
      value: "{{ $toleration.Value }}"
      effect: "{{ $toleration.Effect }}"
      operator: "{{ $toleration.Operator }}"
      {{- if $toleration.TolerationSeconds }}
      tolerationSeconds: {{ $toleration.TolerationSeconds }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if or .ResourceRequests .ResourceLimits }}
    resources:
    {{- if .ResourceRequests }}
      requests:
      {{- range $key, $value := .ResourceRequests }}
        "{{ $key }}": "{{ $value.ToUnstructured }}"
      {{- end }}
    {{- end }}
    {{- if .ResourceLimits }}
      limits:
      {{- range $key, $value := .ResourceLimits }}
        "{{ $key }}": "{{ $value.ToUnstructured }}"
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
